"""Build File Tool into a standalone macOS app, and install it.

    .venv/bin/python -m tools.build_macos              # build dist/FileTool.app
    .venv/bin/python -m tools.build_macos --install    # and put it in /Applications

The result carries its own Python, so it runs on a Mac that has none. PyInstaller
is driven through a generated spec file rather than command line flags, because
only a spec can hand `BUNDLE` the Info.plist: the document types below are what
put File Tool in the "Open with" menu, and they have to be in the bundle before
PyInstaller signs it, not patched in afterwards.

Installing copies the app to /Applications and tells LaunchServices about it, so
the entry appears without a logout or a trip through Finder.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

from tools import icon

PROJECT_ROOT = Path(__file__).resolve().parent.parent

APP_NAME = "FileTool"
DISPLAY_NAME = "File Tool"
BUNDLE_ID = "io.github.grazvy.filetool"
VERSION = "1.0.0"

LSREGISTER = (
    "/System/Library/Frameworks/CoreServices.framework/Frameworks"
    "/LaunchServices.framework/Support/lsregister"
)

# What the app offers to open, named by the uniform type identifiers macOS uses.
# "Alternate" asks to be an option in "Open with" without taking the file type
# over from Preview: a tool the user picks, never one that replaces their default.
DOCUMENT_TYPES = [
    {"name": "PDF document", "uti": "com.adobe.pdf"},
    {"name": "PNG image", "uti": "public.png"},
    {"name": "JPEG image", "uti": "public.jpeg"},
]

# uvicorn picks these at runtime, so PyInstaller cannot see them in the imports.
HIDDEN_IMPORTS = [
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan.on",
]


def info_plist() -> dict:
    """The bundle's Info.plist, as the dictionary PyInstaller writes out."""
    return {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": DISPLAY_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "CFBundlePackageType": "APPL",
        "LSApplicationCategoryType": "public.app-category.utilities",
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
        # The app is a server and a browser tab, so it has no window of its own;
        # without this macOS would keep an idle icon bouncing in the Dock.
        "LSUIElement": True,
        "NSHumanReadableCopyright": "File Tool runs entirely on this machine.",
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeName": kind["name"],
                "CFBundleTypeRole": "Editor",
                "LSHandlerRank": "Alternate",
                "LSItemContentTypes": [kind["uti"]],
            }
            for kind in DOCUMENT_TYPES
        ],
    }


def spec_text(icns: Path | None) -> str:
    """The PyInstaller spec that builds the bundle."""
    return f'''# Generated by tools/build_macos.py — do not edit, it is overwritten.
# noqa
block_cipher = None

a = Analysis(
    [{str(PROJECT_ROOT / "main.py")!r}],
    pathex=[{str(PROJECT_ROOT)!r}],
    binaries=[],
    datas=[({str(PROJECT_ROOT / "frontend")!r}, "frontend")],
    hiddenimports={HIDDEN_IMPORTS!r},
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "pytest", "PyInstaller"],
    cipher=block_cipher,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={APP_NAME!r},
    debug=False,
    strip=False,
    upx=False,
    console=False,
    # macOS delivers opened files as Apple Events, which the app reads itself for
    # as long as it runs; letting the bootloader turn the first one into argv
    # would catch only that one and hide the rest.
    argv_emulation=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name={APP_NAME!r},
)

app = BUNDLE(
    coll,
    name={APP_NAME + ".app"!r},
    icon={str(icns) if icns else None!r},
    bundle_identifier={BUNDLE_ID!r},
    version={VERSION!r},
    info_plist={info_plist()!r},
)
'''


def build(clean: bool = True) -> Path:
    """Build the app. Returns the path to the bundle."""
    if sys.platform != "darwin":
        raise SystemExit("The macOS app can only be built on macOS.")

    work = PROJECT_ROOT / "build"
    dist = PROJECT_ROOT / "dist"
    bundle = dist / f"{APP_NAME}.app"
    if clean and bundle.exists():
        shutil.rmtree(bundle)

    icns = _draw_icon(work / "icon")
    spec = work / f"{APP_NAME}.spec"
    spec.parent.mkdir(parents=True, exist_ok=True)
    spec.write_text(spec_text(icns))

    print(f"Building {bundle.name} …")
    subprocess.run(
        [
            sys.executable, "-m", "PyInstaller", str(spec),
            "--noconfirm", "--distpath", str(dist), "--workpath", str(work),
        ],
        check=True,
        cwd=PROJECT_ROOT,
    )
    if not bundle.is_dir():
        raise SystemExit(f"PyInstaller finished but {bundle} is not there.")
    return bundle


def _draw_icon(directory: Path) -> Path | None:
    """Build the .icns, but never fail the build over the artwork."""
    directory.mkdir(parents=True, exist_ok=True)
    try:
        return icon.build_icns(directory)
    except (OSError, subprocess.CalledProcessError) as error:
        print(f"Carrying on without an icon: {error}", file=sys.stderr)
        return None


def install(bundle: Path, applications: Path = Path("/Applications")) -> Path:
    """Copy the app to /Applications and register it with LaunchServices.

    Falls back to the user's own Applications folder when the machine's is not
    writable, which is the normal case without an administrator password.
    """
    target = applications / bundle.name
    try:
        _replace(bundle, target)
    except PermissionError:
        fallback = Path.home() / "Applications"
        fallback.mkdir(parents=True, exist_ok=True)
        target = fallback / bundle.name
        print(f"{applications} is not writable, installing to {fallback} instead.")
        _replace(bundle, target)

    register(target)
    # The build in dist/ carries the same bundle id. Left registered, it would keep
    # File Tool in "Open with" after the installed copy is removed.
    unregister(bundle)
    return target


def _replace(bundle: Path, target: Path) -> None:
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(bundle, target, symlinks=True)


def register(target: Path) -> None:
    """Tell LaunchServices about the app, so "Open with" lists it right away."""
    _lsregister("-f", target, "register the app with")


def unregister(bundle: Path) -> None:
    """Make LaunchServices forget a copy, so only the installed app is offered.

    `lsregister -u` fails for a copy that was never registered, which is the state
    this asks for, so only a missing lsregister is worth reporting.
    """
    _lsregister("-u", bundle, "unregister the build from", not_registered_ok=True)


def _lsregister(flag: str, path: Path, action: str, not_registered_ok: bool = False) -> None:
    try:
        subprocess.run([LSREGISTER, flag, str(path)], check=True, capture_output=True)
    except subprocess.CalledProcessError as error:
        if not not_registered_ok:
            print(f"Could not {action} macOS: {error}", file=sys.stderr)
    except OSError as error:
        print(f"Could not {action} macOS: {error}", file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="build_macos", description="Build File Tool as a standalone macOS app."
    )
    parser.add_argument(
        "--install", action="store_true", help="Copy the built app to /Applications"
    )
    parser.add_argument(
        "--no-clean", action="store_true", help="Keep the previous bundle instead of removing it"
    )
    args = parser.parse_args(argv)

    bundle = build(clean=not args.no_clean)
    print(f"Built {bundle}")
    if args.install:
        print(f"Installed {install(bundle)}")
        print('File Tool now appears under "Open with" for PDF, PNG and JPG files.')
    else:
        print("Run with --install to put it in /Applications.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
